/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:e06dbafb-8b21-423d-8170-1e5b79a1ef12",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_YPbqESBcN",
    "aws_user_pools_web_client_id": "1acfvbi935g014sjo48837vp7p",
    "oauth": {}
};


export default awsmobile;
